In [87]:
from sqlalchemy import create_engine
import yfinance as yf

In [68]:
engine = create_engine("postgresql://postgres:VolatileMarket@localhost:5432/market_volatility")

In [69]:
engine

Engine(postgresql://postgres:***@localhost:5432/market_volatility)

In [70]:
import pandas as pd

train = pd.read_csv("C:/Users/jungn/OneDrive/Documents/Projects/Market-Volatility-Prediction/data/train.csv")

In [71]:
train.head()

,Unnamed: 0,Date,Open,High,Low,Close,Volume,log_return,future_vol_10,return_5d,...,return_20d,vol_5,vol_10,vol_20,hl_range,oc_range,vol_change,vol_ratio,future_vol_5,future_vol_20
0,0,2015-01-30,165.673388,166.995001,164.483928,164.748245,197729700.0,-0.012655,0.007203,-0.027300,...,-0.030078,0.010537,0.010752,0.010604,0.015242,-0.005584,0.139092,1.242213,0.008649,0.005787
1,1,2015-02-02,165.243903,166.879406,163.434933,166.788544,163107000.0,0.012308,0.006789,-0.017331,...,-0.017234,0.013030,0.010659,0.011045,0.020652,0.009348,-0.175101,1.011470,0.008858,0.005565
2,2,2015-02-03,167.680624,169.208753,167.308921,169.200485,124212900.0,0.014358,0.005791,0.010305,...,0.015349,0.013673,0.011574,0.010748,0.011228,0.009064,-0.238458,0.781280,0.007701,0.004950
3,3,2015-02-04,168.440572,169.646557,168.101904,168.556213,134306700.0,-0.003815,0.005487,0.019397,...,0.020997,0.011638,0.011601,0.010537,0.009164,0.000687,0.081262,0.865132,0.007111,0.004803
4,4,2015-02-05,169.217010,170.406471,169.142672,170.257782,97953200.0,0.010044,0.005027,0.020240,...,0.018657,0.011740,0.011038,0.010417,0.007423,0.006151,-0.270675,0.636579,0.006993,0.005542

In [72]:
train.to_sql(
    "market_data",
    engine,
    if_exists="replace",
    index = False
)

245

In [73]:
val = pd.read_csv("C:/Users/jungn/OneDrive/Documents/Projects/Market-Volatility-Prediction/data/validation.csv")
test = pd.read_csv("C:/Users/jungn/OneDrive/Documents/Projects/Market-Volatility-Prediction/data/test_set.csv")

In [74]:
test = test.drop([0,1])
test = test.rename(columns={"Price":"Date"})

In [75]:
test

,Date,Close,High,Low,Open,Volume,log_return,future_vol_10,return_5d,return_10d,return_20d,vol_5,vol_10,vol_20,hl_range,oc_range,vol_change,vol_ratio
2,2026-01-30,688.3120727539062,690.5402826440542,683.487735152998,688.1330315570439,101835100,-0.002987,0.009946,0.003968,-0.000390,0.014630,0.003578,0.008413,0.006492,0.010246,0.000260,0.044610,1.272511
3,2026-02-02,691.7339477539062,693.2459322689688,685.7756213682558,685.9348095869553,79286500,0.004959,0.009759,0.003861,0.005407,0.017758,0.003546,0.008550,0.006558,0.010799,0.008454,-0.221423,0.997034
4,2026-02-03,685.885009765625,693.2757257351432,680.4140840721383,692.529690413304,107904600,-0.008491,0.009669,-0.008606,0.017483,0.002628,0.004867,0.005572,0.006730,0.018752,-0.009595,0.360945,1.326893
5,2026-02-04,682.5626831054688,687.7948875474046,678.1561081391175,686.7006659106327,105204600,-0.004856,0.009582,-0.013361,0.001152,-0.008157,0.004936,0.004735,0.006673,0.014121,-0.006026,-0.025022,1.265729
6,2026-02-05,674.0379638671875,680.0758839506523,672.2176206040476,677.3404209861714,113610800,-0.012568,0.008763,-0.023943,-0.016626,-0.017496,0.006567,0.005822,0.007187,0.011658,-0.004876,0.079903,1.336301
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,2026-05-26,748.6613159179688,750.1973368284331,746.4469887578754,748.0827892360243,41123600,0.006617,0.009273,0.016035,0.015156,0.048339,0.006331,0.006920,0.006556,0.005009,0.000773,-0.015287,0.857988
82,2026-05-27,748.5316162109375,749.4492351039673,746.2973210478585,748.9505199197505,42106300,-0.000173,0.010244,0.022545,0.016499,0.053044,0.004045,0.006868,0.006362,0.004211,-0.000559,0.023896,0.879419
83,2026-05-28,752.6609497070312,753.2095851254732,747.3047533704411,748.3221518516883,41562600,0.005501,0.011843,0.017850,0.016421,0.058700,0.002724,0.006863,0.006357,0.007845,0.005798,-0.012913,0.868332
84,2026-05-29,754.5361328125,756.1320579864754,752.7507543048832,753.9576670103595,55075700,0.002488,0.012007,0.018357,0.011046,0.051288,0.002658,0.006523,0.006141,0.004481,0.000767,0.325126,1.165460
85,2026-06-01,756.5908203125,758.3264003155792,752.7507376917755,753.4189990020213,43634900,0.002719,0.013466,0.017153,0.025868,0.051242,0.002684,0.004585,0.006141,0.007369,0.004210,-0.207729,0.922789

In [76]:
train["dataset"] = "train"
val["dataset"] = "validation"
test["dataset"] = "test"

In [77]:
train.head()

,Unnamed: 0,Date,Open,High,Low,Close,Volume,log_return,future_vol_10,return_5d,...,vol_5,vol_10,vol_20,hl_range,oc_range,vol_change,vol_ratio,future_vol_5,future_vol_20,dataset
0,0,2015-01-30,165.673388,166.995001,164.483928,164.748245,197729700.0,-0.012655,0.007203,-0.027300,...,0.010537,0.010752,0.010604,0.015242,-0.005584,0.139092,1.242213,0.008649,0.005787,train
1,1,2015-02-02,165.243903,166.879406,163.434933,166.788544,163107000.0,0.012308,0.006789,-0.017331,...,0.013030,0.010659,0.011045,0.020652,0.009348,-0.175101,1.011470,0.008858,0.005565,train
2,2,2015-02-03,167.680624,169.208753,167.308921,169.200485,124212900.0,0.014358,0.005791,0.010305,...,0.013673,0.011574,0.010748,0.011228,0.009064,-0.238458,0.781280,0.007701,0.004950,train
3,3,2015-02-04,168.440572,169.646557,168.101904,168.556213,134306700.0,-0.003815,0.005487,0.019397,...,0.011638,0.011601,0.010537,0.009164,0.000687,0.081262,0.865132,0.007111,0.004803,train
4,4,2015-02-05,169.217010,170.406471,169.142672,170.257782,97953200.0,0.010044,0.005027,0.020240,...,0.011740,0.011038,0.010417,0.007423,0.006151,-0.270675,0.636579,0.006993,0.005542,train

In [78]:
all_data = pd.concat(
    [train,val,test],
    ignore_index=True
)

In [79]:
all_data["dataset"].value_counts()

dataset
train         2245
validation     502
test            84
Name: count, dtype: int64

In [80]:
all_data.to_sql(
    "market_data",
    engine,
    if_exists="replace",
    index = False
)

831

In [81]:
all_data.columns.tolist()

['Unnamed: 0',
 'Date',
 'Open',
 'High',
 'Low',
 'Close',
 'Volume',
 'log_return',
 'future_vol_10',
 'return_5d',
 'return_10d',
 'return_20d',
 'vol_5',
 'vol_10',
 'vol_20',
 'hl_range',
 'oc_range',
 'vol_change',
 'vol_ratio',
 'future_vol_5',
 'future_vol_20',
 'dataset']

In [83]:
all_data = all_data.drop(columns = ["Unnamed: 0"])

all_data["Date"] = pd.to_datetime(all_data["Date"])

In [84]:
all_data

,Date,Open,High,Low,Close,Volume,log_return,future_vol_10,return_5d,return_10d,...,vol_5,vol_10,vol_20,hl_range,oc_range,vol_change,vol_ratio,future_vol_5,future_vol_20,dataset
0,2015-01-30,165.673388,166.995001,164.483928,164.748245,197729700.0,-0.012655,0.007203,-0.027300,0.002158,...,0.010537,0.010752,0.010604,0.015242,-0.005584,0.139092,1.242213,0.008649,0.005787,train
1,2015-02-02,165.243903,166.879406,163.434933,166.788544,163107000.0,0.012308,0.006789,-0.017331,0.001437,...,0.013030,0.010659,0.011045,0.020652,0.009348,-0.175101,1.011470,0.008858,0.005565,train
2,2015-02-03,167.680624,169.208753,167.308921,169.200485,124212900.0,0.014358,0.005791,0.010305,0.013664,...,0.013673,0.011574,0.010748,0.011228,0.009064,-0.238458,0.781280,0.007701,0.004950,train
3,2015-02-04,168.440572,169.646557,168.101904,168.556213,134306700.0,-0.003815,0.005487,0.019397,0.004814,...,0.011638,0.011601,0.010537,0.009164,0.000687,0.081262,0.865132,0.007111,0.004803,train
4,2015-02-05,169.21701,170.406471,169.142672,170.257782,97953200.0,0.010044,0.005027,0.020240,0.000097,...,0.011740,0.011038,0.010417,0.007423,0.006151,-0.270675,0.636579,0.006993,0.005542,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2826,2026-05-26,748.0827892360243,750.1973368284331,746.4469887578754,748.6613159179688,41123600,0.006617,0.009273,0.016035,0.015156,...,0.006331,0.006920,0.006556,0.005009,0.000773,-0.015287,0.857988,NaN,NaN,test
2827,2026-05-27,748.9505199197505,749.4492351039673,746.2973210478585,748.5316162109375,42106300,-0.000173,0.010244,0.022545,0.016499,...,0.004045,0.006868,0.006362,0.004211,-0.000559,0.023896,0.879419,NaN,NaN,test
2828,2026-05-28,748.3221518516883,753.2095851254732,747.3047533704411,752.6609497070312,41562600,0.005501,0.011843,0.017850,0.016421,...,0.002724,0.006863,0.006357,0.007845,0.005798,-0.012913,0.868332,NaN,NaN,test
2829,2026-05-29,753.9576670103595,756.1320579864754,752.7507543048832,754.5361328125,55075700,0.002488,0.012007,0.018357,0.011046,...,0.002658,0.006523,0.006141,0.004481,0.000767,0.325126,1.165460,NaN,NaN,test
2830,2026-06-01,753.4189990020213,758.3264003155792,752.7507376917755,756.5908203125,43634900,0.002719,0.013466,0.017153,0.025868,...,0.002684,0.004585,0.006141,0.007369,0.004210,-0.207729,0.922789,NaN,NaN,test

In [85]:
all_data.to_sql(
    "market_data",
    engine,
    if_exists="replace",
    index=False
)

831

In [86]:
query = """
SELECT MAX("Date")
FROM market_data
"""

latest_date = pd.read_sql(
    query,
    engine
).iloc[0,0]

print(latest_date)

2026-06-01 00:00:00

In [88]:
new_data = yf.download(
    "SPY",
    start=latest_date.strftime("%Y-%m-%d"),
    auto_adjust=True
)

[*********************100%***********************]  1 of 1 completed

In [89]:
new_data.tail()

Price            Close        High         Low        Open    Volume
Ticker             SPY         SPY         SPY         SPY       SPY
Date
2026-07-15  754.809998  755.580017  750.200012  754.239990  43844800
2026-07-16  750.719971  754.570007  747.880005  752.760010  46409800
2026-07-17  743.289978  747.289978  740.799988  742.080017  62651000
2026-07-20  742.090027  748.729980  741.510010  747.059998  50422300
2026-07-21  748.280029  749.039978  744.179993  746.289978  34263300

In [90]:
new_data = new_data.reset_index()

In [91]:
new_data

Price        Date       Close        High         Low        Open    Volume
Ticker                    SPY         SPY         SPY         SPY       SPY
0      2026-06-01  756.590820  758.326400  752.750738  753.418999  43634900
1      2026-06-02  757.618225  758.446109  754.805464  755.084774  31581900
2      2026-06-03  752.301880  756.850160  751.633619  756.201867  51402500
3      2026-06-04  755.144592  756.361428  749.538978  750.167364  49923000
4      2026-06-05  735.654785  750.885567  733.640017  750.376868  93989400
5      2026-06-08  737.320435  743.424764  736.293113  741.449811  49319100
6      2026-06-09  735.156067  744.980793  720.733262  741.719176  87683500
7      2026-06-10  723.565918  736.482654  723.466199  731.505486  60341300
8      2026-06-11  735.864258  738.098492  722.548526  726.887384  86330500
9      2026-06-12  739.843994  742.527084  733.141291  738.806688  57079500
10     2026-06-15  752.890381  754.735603  749.828262  749.917997  60176400
11     2026-06-16  748.401978  753.498832  747.953122  752.611105  67093100
12     2026-06-17  739.056030  750.217279  737.320450  749.359442  85945200
13     2026-06-18  746.739990  748.229980  743.859985  747.760010  80875700
14     2026-06-22  744.390015  750.179993  743.130005  747.700012  46628100
15     2026-06-23  733.580017  739.630005  732.299988  733.809998  66846800
16     2026-06-24  733.239990  739.950012  730.840027  735.169983  57439500
17     2026-06-25  734.299988  739.369995  729.599976  738.909973  53934400
18     2026-06-26  728.989990  736.530029  716.580017  728.950012  71034000
19     2026-06-29  741.000000  741.559998  732.090027  736.530029  58035200
20     2026-06-30  746.770020  748.020020  740.890015  741.289978  55626000
21     2026-07-01  745.760010  749.440002  742.380005  745.000000  47100900
22     2026-07-02  744.780029  751.309998  740.030029  747.400024  57447800
23     2026-07-06  751.280029  752.409973  747.409973  748.739990  50673300
24     2026-07-07  747.710022  750.960022  745.210022  750.219971  43721500
25     2026-07-08  745.400024  746.150024  739.510010  743.159973  43767400
26     2026-07-09  751.710022  751.969971  745.590027  747.349976  41441700
27     2026-07-10  754.950012  755.419983  748.099976  752.049988  42191300
28     2026-07-13  749.169983  753.909973  748.000000  752.469971  44013600
29     2026-07-14  751.830017  753.340027  748.659973  750.909973  35143100
30     2026-07-15  754.809998  755.580017  750.200012  754.239990  43844800
31     2026-07-16  750.719971  754.570007  747.880005  752.760010  46409800
32     2026-07-17  743.289978  747.289978  740.799988  742.080017  62651000
33     2026-07-20  742.090027  748.729980  741.510010  747.059998  50422300
34     2026-07-21  748.280029  749.039978  744.179993  746.289978  34263300

In [92]:
new_data = new_data[
    new_data["Date"] > latest_date
]

In [93]:
print(new_data.head())
print(new_data.tail())
print(len(new_data))

Price        Date       Close        High         Low        Open    Volume
Ticker                    SPY         SPY         SPY         SPY       SPY
1      2026-06-02  757.618225  758.446109  754.805464  755.084774  31581900
2      2026-06-03  752.301880  756.850160  751.633619  756.201867  51402500
3      2026-06-04  755.144592  756.361428  749.538978  750.167364  49923000
4      2026-06-05  735.654785  750.885567  733.640017  750.376868  93989400
5      2026-06-08  737.320435  743.424764  736.293113  741.449811  49319100
Price        Date       Close        High         Low        Open    Volume
Ticker                    SPY         SPY         SPY         SPY       SPY
30     2026-07-15  754.809998  755.580017  750.200012  754.239990  43844800
31     2026-07-16  750.719971  754.570007  747.880005  752.760010  46409800
32     2026-07-17  743.289978  747.289978  740.799988  742.080017  62651000
33     2026-07-20  742.090027  748.729980  741.510010  747.059998  50422300
34     2026-07-21  748.280029  749.039978  744.179993  746.289978  34263300
34

In [96]:
market_cols = pd.read_sql(
    """
    SELECT *
    FROM market_data
    LIMIT 1
    """,
    engine
)

print(market_cols.columns.tolist())

['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'log_return', 'future_vol_10', 'return_5d', 'return_10d', 'return_20d', 'vol_5', 'vol_10', 'vol_20', 'hl_range', 'oc_range', 'vol_change', 'vol_ratio', 'future_vol_5', 'future_vol_20', 'dataset']

In [95]:
new_data.to_sql(
    "market_data",
    engine,
    if_exists="append",
    index = False
)

ProgrammingError: (psycopg2.errors.UndefinedColumn) column "('Date', '')" of relation "market_data" does not exist
LINE 1: INSERT INTO market_data ("('Date', '')", "('Close', 'SPY')",...
                                 ^

[SQL: INSERT INTO market_data ("('Date', '')", "('Close', 'SPY')", "('High', 'SPY')", "('Low', 'SPY')", "('Open', 'SPY')", "('Volume', 'SPY')") VALUES (%(A'Date',_''Z__0)s, %(A'Close',_'SPY'Z__0)s, %(A'High',_'SPY'Z__0)s, %(A'Low',_'SPY'Z__0)s, %(A'Open',_ ... 4867 characters truncated ... %(A'High',_'SPY'Z__33)s, %(A'Low',_'SPY'Z__33)s, %(A'Open',_'SPY'Z__33)s, %(A'Volume',_'SPY'Z__33)s)]
[parameters: {"A'High',_'SPY'Z__0": 758.4461093852723, "A'Low',_'SPY'Z__0": 754.805464031348, "A'Open',_'SPY'Z__0": 755.0847737682097, "A'Close',_'SPY'Z__0": 757.6182250976562, "A'Date',_''Z__0": datetime.datetime(2026, 6, 2, 0, 0), "A'Volume',_'SPY'Z__0": 31581900, "A'High',_'SPY'Z__1": 756.8501599793441, "A'Low',_'SPY'Z__1": 751.6336185743088, "A'Open',_'SPY'Z__1": 756.2018667594974, "A'Close',_'SPY'Z__1": 752.3018798828125, "A'Date',_''Z__1": datetime.datetime(2026, 6, 3, 0, 0), "A'Volume',_'SPY'Z__1": 51402500, "A'High',_'SPY'Z__2": 756.3614281257201, "A'Low',_'SPY'Z__2": 749.5389775481502, "A'Open',_'SPY'Z__2": 750.1673635570705, "A'Close',_'SPY'Z__2": 755.1445922851562, "A'Date',_''Z__2": datetime.datetime(2026, 6, 4, 0, 0), "A'Volume',_'SPY'Z__2": 49923000, "A'High',_'SPY'Z__3": 750.8855669656407, "A'Low',_'SPY'Z__3": 733.6400171295905, "A'Open',_'SPY'Z__3": 750.3768677170906, "A'Close',_'SPY'Z__3": 735.65478515625, "A'Date',_''Z__3": datetime.datetime(2026, 6, 5, 0, 0), "A'Volume',_'SPY'Z__3": 93989400, "A'High',_'SPY'Z__4": 743.4247643242134, "A'Low',_'SPY'Z__4": 736.2931129658897, "A'Open',_'SPY'Z__4": 741.4498108327123, "A'Close',_'SPY'Z__4": 737.3204345703125, "A'Date',_''Z__4": datetime.datetime(2026, 6, 8, 0, 0), "A'Volume',_'SPY'Z__4": 49319100, "A'High',_'SPY'Z__5": 744.9807928982774, "A'Low',_'SPY'Z__5": 720.7332622187009, "A'Open',_'SPY'Z__5": 741.7191759970133, "A'Close',_'SPY'Z__5": 735.1560668945312, "A'Date',_''Z__5": datetime.datetime(2026, 6, 9, 0, 0), "A'Volume',_'SPY'Z__5": 87683500, "A'High',_'SPY'Z__6": 736.4826536495077, "A'Low',_'SPY'Z__6": 723.4661992814284, "A'Open',_'SPY'Z__6": 731.5054857614351, "A'Close',_'SPY'Z__6": 723.56591796875, "A'Date',_''Z__6": datetime.datetime(2026, 6, 10, 0, 0), "A'Volume',_'SPY'Z__6": 60341300, "A'High',_'SPY'Z__7": 738.0984921563339, "A'Low',_'SPY'Z__7": 722.5485255148498, "A'Open',_'SPY'Z__7": 726.8873842592473, "A'Close',_'SPY'Z__7": 735.8642578125, "A'Date',_''Z__7": datetime.datetime(2026, 6, 11, 0, 0), "A'Volume',_'SPY'Z__7": 86330500, "A'High',_'SPY'Z__8": 742.5270843334097, "A'Low',_'SPY'Z__8": 733.1412911200548 ... 104 parameters truncated ... "A'Date',_''Z__25": datetime.datetime(2026, 7, 9, 0, 0), "A'Volume',_'SPY'Z__25": 41441700, "A'High',_'SPY'Z__26": 755.4199829101562, "A'Low',_'SPY'Z__26": 748.0999755859375, "A'Open',_'SPY'Z__26": 752.0499877929688, "A'Close',_'SPY'Z__26": 754.9500122070312, "A'Date',_''Z__26": datetime.datetime(2026, 7, 10, 0, 0), "A'Volume',_'SPY'Z__26": 42191300, "A'High',_'SPY'Z__27": 753.9099731445312, "A'Low',_'SPY'Z__27": 748.0, "A'Open',_'SPY'Z__27": 752.469970703125, "A'Close',_'SPY'Z__27": 749.1699829101562, "A'Date',_''Z__27": datetime.datetime(2026, 7, 13, 0, 0), "A'Volume',_'SPY'Z__27": 44013600, "A'High',_'SPY'Z__28": 753.3400268554688, "A'Low',_'SPY'Z__28": 748.6599731445312, "A'Open',_'SPY'Z__28": 750.9099731445312, "A'Close',_'SPY'Z__28": 751.8300170898438, "A'Date',_''Z__28": datetime.datetime(2026, 7, 14, 0, 0), "A'Volume',_'SPY'Z__28": 35143100, "A'High',_'SPY'Z__29": 755.5800170898438, "A'Low',_'SPY'Z__29": 750.2000122070312, "A'Open',_'SPY'Z__29": 754.239990234375, "A'Close',_'SPY'Z__29": 754.8099975585938, "A'Date',_''Z__29": datetime.datetime(2026, 7, 15, 0, 0), "A'Volume',_'SPY'Z__29": 43844800, "A'High',_'SPY'Z__30": 754.5700073242188, "A'Low',_'SPY'Z__30": 747.8800048828125, "A'Open',_'SPY'Z__30": 752.760009765625, "A'Close',_'SPY'Z__30": 750.719970703125, "A'Date',_''Z__30": datetime.datetime(2026, 7, 16, 0, 0), "A'Volume',_'SPY'Z__30": 46409800, "A'High',_'SPY'Z__31": 747.2899780273438, "A'Low',_'SPY'Z__31": 740.7999877929688, "A'Open',_'SPY'Z__31": 742.0800170898438, "A'Close',_'SPY'Z__31": 743.2899780273438, "A'Date',_''Z__31": datetime.datetime(2026, 7, 17, 0, 0), "A'Volume',_'SPY'Z__31": 62651000, "A'High',_'SPY'Z__32": 748.72998046875, "A'Low',_'SPY'Z__32": 741.510009765625, "A'Open',_'SPY'Z__32": 747.0599975585938, "A'Close',_'SPY'Z__32": 742.0900268554688, "A'Date',_''Z__32": datetime.datetime(2026, 7, 20, 0, 0), "A'Volume',_'SPY'Z__32": 50422300, "A'High',_'SPY'Z__33": 749.0399780273438, "A'Low',_'SPY'Z__33": 744.1799926757812, "A'Open',_'SPY'Z__33": 746.2899780273438, "A'Close',_'SPY'Z__33": 748.280029296875, "A'Date',_''Z__33": datetime.datetime(2026, 7, 21, 0, 0), "A'Volume',_'SPY'Z__33": 34263300}]
(Background on this error at: https://sqlalche.me/e/20/f405)